name: Semgrep

on:
  pull_request_target: {}
  push:
    branches: ["master", "main"]
jobs:
  semgrep:
    name: Scan
    runs-on:
      labels: ubuntu-22.04-2cpu-8ram-75ssd
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]' && github.actor != 'snyk-bot')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
